---
title           : "Preregistration: Bat Community Structure In the Cypress Hills pre/post White-Nose Syndrome"
shorttitle      : "PreReg: Bat Community Structure in Cypress"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"
author: 
  - name        : Sophia Fan
    affiliation : 1
  - name        : Keerthi Krutha
    affiliation : 3
  - name        : Javad Meghrazi
    affiliation : 1
  - name        : Tanya Strydom
    affiliation : 2
  - name        : Hannah Wilson
    affiliation : 3
      
affiliation:
    
  - id          : 1
    institution : University of British Columbia
  - id          : 2
    institution : Université de Montréal
  - id          : 3
    institution : University of Regina
output: prereg::cos_prereg
editor_options: 
  markdown: 
    wrap: 72
bibliography: references.bib
---

# Study Information

## Title

`r rmarkdown::metadata$title` Effects of white-nose syndrome (WNS)
on bat community structure in Cypress Hills, Saskatchewan, Canada.

## Description

White-nose syndrome (WNS) is an infectious fungal disease of bats 
caused by *Pseudogymnoascus destructans* @jachowski2014.
Since its first detection it has affected and killed more than 6 million 
hibernating bats in eastern North America @jachowski2014. 
WNS affects different bat species differentially with the little 
brown bat (*Myotis lucifugus*) being the most adversely affected 
species @frick2010a, @hoyt2021. Loss of bat species and regional 
scale bat populations can lead to loss of the essential 
ecosystem functions of pollination and seed dispersal (CITATION).
In North America, major areas affected by this disease are in eastern USA and eastern Canada 
with a few sites in central USA affected. However, the fungus is predicted to be spreading westward each year.
In 2021, the first report of WNS with no bat mortality was reported from the Cypress Hills Interprovincial Park 
in central Canadian province of Saskatchewan. Due to this report, the differential gradient in the effect of WNS on different bat species, the adverse effects of the fungus on 
bat populations and the important roles which bats play in an ecosystem there 
is a dire need for bat community-level studies and monitoring programs on bat populations @hoyt2021. 
Therefore, to understand the gravity of the issue, using the data collected since 1991 
from the Cypress Hills Interprovincial Park we aim to compare bat community data before 
and after the introduction of WNS. We also aim to construct population projection models 
for all the species of bats monitored in this area. The results of our study will aid in directing conservation efforts for bats in this region in Canada.


## Hypotheses

Results from previous studies in eastern North America suggest how white nose syndrome (WNS) may affect bat populations in Cypress hill region of Saskatchewan Province.

## Directional Predictions
Specifically, we predict populations of little brown bats (*Myotis lucifugus*) to decrease when affected by WNS 
and silver-haired bats (*Lasionycteris noctivagans*) to increase (CITATION?).


# Design Plan

<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->

## Study type

**Observational Study**. Data is collected from study subjects that are
not randomly assigned to a treatment. This includes surveys, natural
experiments, and regression discontinuity designs.

## Blinding

No blinding is involved in this study.

## Study design

Design: Case-control design @Mann 2003 equivalent to a two-group design. 
Assumption: No two same individual bats were sampled before and after *P. destructans* detection. Therefore, we will be using unpaired design. 

## Randomization

Not applicable

# Sampling Plan

## Existing data

1.Registration prior to analysis of the data (See explanation) 
2. Registration prior to creation of data. 
3. We say both because a part of the 
data is already collected but a part of it will take until 2030 to be collected, 
only after which it can be used for analysis.

## Explanation of existing data

Our access to the dataset has been limited because, all team members except Ms. Hannah Wilson 
come from other departments and laboratories with no prior studies conducted on bats. 
Ms. Wilson is a new student to the bat research group to the University of Regina and started in September 2021. 
The dataset we plan to use for our study has been collected by multiple trained researchers using the above protocols
since 1991. 
Ms. Wilson has seen the dataset with data from 1991-1992 and ca. 2019 but 
has not conducted any form of statistical analysis with it. 
Also, as authors of this study, none of us are aware of any patterns 
or summary statistics relating to the effect of a fungal disease on 
bats of this dataset even though there are publications/results from 
previous studies conducted by other researchers. We plan to only conduct 
any detailed analysis with the data only after 2030 
since the study is aimed to nine-years in length.

## Data collection procedures

Study site: West block, Cypress Hills Provincial Park, Saskatchewan, Canada.
Study locations: Already established capture locations for bats along Battle Creek, 
established by the University of Regina bat research group (Wilson pers. comm.).

Sampling period: Mid-June to mid-august every year. Samples will be collected until August 2030. 
Data points from this same period will be used from records prior to P. destructans incidence starting from August 1991.
 
Data collection methods: We will capture bats using mist nets
following an established protocol @Farrell and Gannon 1999 from ca.2021-2030. 
Specifically, we will set up mist nets at the established sites along Battle Creek per night during the entire length of the study. 
We will setup nets for three hours after last light and check the nets for every 10min in the first hour 
and every 15min in the subsequent two hours.
We will capture and handle bats by nitrile-gloves covered hands. 
Once a bat is caught it will be moved away from the mist-net site 
in order to avoid attracting other individuals to the captured bat’s distress call.
We will record the age, sex, mass and species of the bat.
In order to attribute the possible difference in bat population to the fungal disease 
we will collect samples of *P. destructans* by swabbing wings and muzzle of the bat follwing @Zakul et al. 2016.
We will analyse swabs using qPCR (@Zakul et al. 2016).

We will also measurements temperature, cloud cover and wind speed while sampling for bats. 
In case of rain or if wind speed is above 20km/s, we will stop sampling.
When recording a capture, we will record the date of sampling in the ISO format along with a three-letter code of the sampling location at Battle creek, 
the genus and species of bat being captured and initials of the personnel collecting the capture will be recorded. 
A database of abbreviations and geographic coordinates will be maintained by the researchers.
Every year, we will plan to sample around similar dates as the previous year.


## Sample size

For our final analysis, we will aim to have collected about 2000 samples. 

## Sample size rationale

We do not have control over how many bats will be captured in a night. Therefore, from anecdotal knowledge and previous experience 
we estimate to capture anywhere between 100-200 bats. After twenty years of data collection we will have collected around 2000 bats.

## Stopping rule

```{=html}
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->
```
Data collection will end each year in mid-August. The field station
where researchers live during the field season is owned by the
University of Regina, who use the station for an undergraduate class
during the last week of August. The field station is closed after that,
so data collection will stop mid-August

-bats start to migrate in mid-aug once pups can fly well (Lano, Laci)

The project overall will end in 2030. White-Nose Syndrome was first
detected in Saskatchewan in 2021. Ending the project 10 years after WNS
was first detected allows us to observe bat community structure at the
start of the disease, directly after it should have killed the largest
number of bats, and ten years later when it should have become endemic
to the population.

# Variables

<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

## Manipulated variables

```{=html}
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->
```
Not applicable

## Measured variables

```{=html}
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->
```
We are going to be measuring the population size of the bat species in the Cypress Hills before and after the detection of White-nose Syndrome. We will measure this by counting how many bats of each we catch in mist nets each year.  


## Indices

```{=html}
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->
```
Enter your response here.

# Analysis Plan

```{=html}
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->
```
## Statistical models

```{=html}
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->
```
Enter your response here.

## Transformations

```{=html}
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->
```
Enter your response here.

## Inference criteria

```{=html}
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->
```
## Data exclusion

```{=html}
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->
```
Enter your response here.

## Missing data

```{=html}
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->
```
Enter your response here.

## Exploratory analyses (optional)

```{=html}
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->
```
Enter your response here.

# Other

## Other (Optional)

<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.

# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
