---
title: "Proposed models"
author: "Javad"
date: "10/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Here is a proposed model for this problem: 

<!-- I'm assuming that our data is population sizes of all species (not frequencies in relation to eachother, in this case I should change it a bit). -->
Population size of each of species would change based on the following equation: 
$$
N_{i,t+1} = N_{i,t}r_i (1+\frac{K_i-N_{i,t}- \sum_{i = 1}^{n}{\alpha_{i,j} N_{j,t}}}{K})-I_{i,t}
$$
Where:
$N_{i,t}$ is the population size of species i at time t
$r_i$ is the intrinsic growth rate of species i
$K_i$ is the carrying capacity for species i
$\alpha_{i,j} $ is the coefficent for competition effect of species j on species i. 
$I_{i,t}$ is the number of individuals infected with WNS at time t. It's assumed that all of these individuals will dye before next time point. This parameter is calculated as follow: 
$$
I_{i,t+1}=d_iI_{i,t}\frac{N_{i,t}}{k_i}
$$
Where $d_i$ is the transmission rate of WNS in species i.
It's assumed that transmission of diseas is density dependent. 

Estimation of coefficients: 
$r$, $K$ and $\alpha$: They should be calculated based on the data gathered sofar (1991-2021) using genetic algorithm (or any other optimization method?).

$d$: depends on the objective of study:
1- If we are going to make predictions for future dynamics of populations, previous studies should be used to estimate this parameter. It should be considered that $d$ probably won't stay constant over time and evolutionary dynamics of host and parasite would affect it.
2- If we are going to estimate $d$ in each of these populations after the end of study, similar method as other coefficients can be used.

Note that in both cases an initial number of infected individuals at year 2021 is required ($I_{i,t=2021}$).

